### ISSUE TITLE
Adding a custom style rule...?

### ISSUE THREAD

**Issue by calculuschild** [elirasza/stylelint-stylistic#10]
This may be a dumb question: Our group uses a few other styling rules that StyleLint never supported. Now that those have migrated here, I'm wondering what is the best approach to adding our own rules so they can work alongside the same config file. Do you accept PRs for custom rules? Do I make my own entire plugin?

I'm still trying to figure out the postcss/stylelint ecosystem and am not sure what the best practices are.

**Comment by elirasza** [comment]
Hello ! I think the best practice would be to write your own plugin so we can split the maintaining, but I can accept PR if you want.

**Comment by calculuschild** [comment]
Maybe a better question:  I like that all of the "style" rules now live under the common "stylistic" namespace. If I make my own package, can I use `stylistic/my-custom-rule` to make it more easily searchable, etc.? Just trying to think of user accessibility.

On the other hand, I'm all for condensing a bunch of tiny packages into one larger one like this so everything is tidy and collected. I'm happy to maintain *my part* here, but I can understand if this project only wants to maintain the old official stylelint rules.

**Comment by elirasza** [comment]
I think that namespaces should be related to a package, not a functional group, to avoid same-name conflicts due to uncoordinated work.

Regarding one package VS several tiny packages, I think both options are viable and have their advantages. For now, I'm hosting the old rules for backwards compatibility, so I think splitting the work is more realistic.

That being said, if you are keen on creating new rules, why not forking this package ? There would be no problem for you using the same namespace, and we will be able to merge things together in the future.
