### ISSUE TITLE
`string-quotes`: fix @charset quotes

### ISSUE THREAD

**Issue by Mouvedia** [elirasza/stylelint-stylistic#16]
### Rationale

https://github.com/stylelint/stylelint/pull/2959#discussion_r145541376
https://github.com/stylelint/stylelint/issues/7060

### What minimal example or steps are needed to reproduce the bug?

```css
@charset 'utf-8';
```

### What minimal configuration is needed to reproduce the bug?

```jsonc
{
  "fix": true,
  "rules": {
    "string-quotes": "single" // or "double"
  }
}
```

### How did you run Stylelint?

https://stylelint.io/demo

### What did you expect to happen?

after `--fix`

```css
@charset "utf-8";
```

### What actually happened?

after `--fix`

```css
@charset 'utf-8';
```

**Comment by firefoxic** [comment]
The new plugin [also inherited this bug](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACYAWBDATgZxgFwAIByAVQBUAxAWgA4iBuAHQDskBLAWwAcJNCi8MbADow2bAxYgANCABmbADYwAcug5xEMAB7quy0eJngIzBQHMEIYCwIFG8ttofwCeTAFcY02-ZD6PczZmbBcCAG1fOwckbDwAT0U2OLYwAHo4xJgk5jwqAKDmB18AXR9maJBPZVCEAhsKuz9YhKSU9LjMYPMqAEcPCEFa1wcoCA8AI2VixoBfFlnjSDM2cwpeDnQ8KwArbFNjWC5sKwbKzOUcvDCHRS2ha5lfGIvkvFSM1uzgvILgm5AdyGjwWIFmQA).

@Mouvedia Could you please duplicate this issue [here](https://github.com/stylelint-stylistic/stylelint-stylistic/issues/new?assignees=&labels=&projects=&template=REPORT_A_BUG.yml) so that I can deal with it as soon as possible.

**Comment by Mouvedia** [comment]
stylelint-stylistic/stylelint-stylistic#13
